config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users

  concern :votable do
    member do
      post :vote_up, :vote_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, concerns: %i[votable commentable] do
    resource :subscription, only: %i[create destroy]
    resources :answers, concerns: %i[votable commentable], shallow: true, only: [:create, :update, :destroy] do
      patch :choose_the_best, on: :member
    end
  end

  resources :attachments, only: [:destroy]
  resources :links, only: [:destroy]
  resources :badges, only: [:index]

  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        collection do
          get :me
          get :all
        end
      end

      resources :questions, only: %i[index show create update destroy], shallow: true do
        resources :answers, only: %i[index show create update destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/question.rb
class Question < ApplicationRecord
  include Votable
  include Commentable
  
  belongs_to :user

  has_one :badge, dependent: :destroy

  has_many :answers, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  accepts_nested_attributes_for :badge, reject_if: :all_blank

  validates :title, :body, presence: true

  def subscribe(user)
    subscriptions.create!(user_id: user.id)
  end

  def unsubscribe(user)
    subscriptions.where(user_id: user.id).delete_all
  end

  # after_create :calculate_reputation


  # private

  # def calculate_reputation
  #   # ReputationJob.perform_later(self)
  #   Services::Reputation.calculate(self)
  # end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :load_question, only: %i[show update destroy]

  def index
    @questions = Question.all
    authorize! :read, @questions
    render json: @questions
  end

  def show
    authorize! :read, @question
    render json: @question
  end

  def create
    @question = current_resource_owner.questions.new(question_params)
    authorize! :create, @question
    @question.save
    render json: @question
  end

  def update
    authorize! :update, @question
    @question.update!(question_params)
    render json: @question
  end

  def destroy
    authorize! :destroy, @question
    @question.destroy
    render json: @question
  end

  private

  def question_params
    params.require(:question).permit(:body, :title, links_attributes: [:id, :name, :url, :_destroy], reward_attributes: [:name, :file])
  end

  def load_question
    @question = Question.find(params[:id])
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController 
  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :edit, :update, :destroy]

  after_action :publish_question, only: [:create]

  include Voted

  authorize_resource

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
    @answer.links.new
  end

  def new
    @question = Question.new
    @question.links.new
    @question.badge ||= Badge.new
  end

  def edit; end

  def create
    @question = current_user.questions.new(question_params)

    if @question.save
      @question.subscribe(current_user)
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    authorize! :update, @question
    @question.update(question_params)
  end

  def destroy
    authorize! :destroy, @question
    @question.destroy
    redirect_to questions_path
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:title, :body, files: [], links_attributes: [:name, :url, :id, :_destroy], badge_attributes: [:title, :image])
  end

  def publish_question
    return if @question.errors.any?

    ActionCable.server.broadcast(
      'questions_channel',
      ApplicationController.render(
        partial: 'questions/short_question',
        locals: { question: @question }
      )
    )
    
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_link_fields.html.slim
.nested-fields
  .field
    = f.label :name, 'Link name'
    = f.text_field :name
  .field
    = f.label :url, 'Link url'
    = f.text_field :url
  = link_to_remove_association "Remove link", f

app/views/questions/_links_list.html.slim
.links
  p Links:
  ul
    - @question.links.each do |link|
      div class="link-#{link.id}"
        li= link_to link.name, link.url
        - if current_user&.author_of?(@question)
          p= link_to 'Delete link', link_path(link), method: :delete, remote: true

app/views/questions/_question.html.slim
.question
  h1= @question.title
  = render '/subscriptions/subscription', resource: @question
  p= @question.body

  - if @question.files.attached?
    - @question.files.each do |file|
      div id=file.id
        p= link_to file.filename.to_s, url_for(file)
        p= link_to 'Delete file', attachment_path(file), method: :delete, remote: true

  .question_comments
    = render 'comments/comments', resource: @question
  .add_comment
  = render 'comments/form', resource: @question
  
  .vote
    p Vote:
    div class="#{@question.class}-#{@question.id}"
      .rating
        =  "rating: #{@question.rating}"
      - unless current_user&.author_of?(@question)
        .voting
          = link_to 'up', polymorphic_path(@question, action: :vote_up), method: :post, remote: true, data: { type: :json }
          span= ' | '
          = link_to 'down', polymorphic_path(@question, action: :vote_down), method: :post, remote: true, data: { type: :json }
        .re-vote
          = link_to 'cancel your vote', polymorphic_path(@question, action: :cancel_vote),
                                        class: "cancel-vote-link #{'hidden' unless current_user&.already_voted?(@question.id)}", 
                                        method: :delete, remote: true, data: {type: :json}

  - if current_user&.author_of?(@question)
    p= link_to 'Delete question', question_path(@question), method: :delete
    p= link_to 'Edit question', '#', class: 'edit-question-link', data: { question_id: @question.id }
    = form_with model: @question, class: 'hidden', html: { id: "edit-question" } do |f|
      = f.label :title, 'Question title'
      = f.text_area :title
      = f.label :body, 'Question body'
      = f.text_area :body
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
      = f.fields_for :links do |l|
      .links
        = link_to_add_association 'Add link', f, :links, partial: 'questions/link_fields'
      = f.submit 'Save'

app/views/questions/_short_question.html.slim
p= question.title
= question.body
hr

app/views/questions/index.html.slim
- if can?(:create, Question)
  p= link_to 'Ask question', new_question_path

.questions
  - @questions.each do |q|
    p= q.title
    = q.body
    hr

app/views/questions/new.html.slim
.question-errors
  = render 'shared/errors', resource: @question

= form_with model: @question do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true, direct_upload: true
  
  p Links:
  p
    = f.fields_for :links do |l|
      = render 'link_fields', f: l
    .links
      = link_to_add_association 'Add link', f, :links
      
  p Badge:
  p
    = f.fields_for :badge do |b|
      p
        = b.label :title, 'Badge title'
        = b.text_field :title
      p
        = b.label :image
        = b.file_field :image
  p= f.submit 'Ask'

app/views/questions/show.html.slim
= render 'shared/errors', resource: @answer

= render @question

- if @question.files.attached?
  - @question.files.each do |file|
    p= link_to file.filename.to_s, url_for(file)

.question_links
  = render 'links_list'

.answers
  = render @question.answers

.answer-errors
  = render 'shared/errors', resource: @answer

.question-errors
  = render 'shared/errors', resource: @question

- if !current_user.nil?
  = form_with model: [@question, @answer], class: 'new-answer' do |f|
    p
      = f.label :body
      = f.text_area :body
    p
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
    p Links:
    p
      = f.fields_for :links do |l|
        = render 'link_fields', f: l
      .links
        = link_to_add_association 'Add link', f, :links, partial: 'questions/link_fields'
    p= f.submit 'Answer'

app/views/questions/subscribe.js.erb
$('.subscription').html('<%= j render partial: 'subscription' %>');

app/views/questions/unsubscribe.js.erb
$('.subscription').html('<%= j render partial: 'subscription' %>');

app/views/questions/update.js.erb
$('.question-errors').html('<%= render 'shared/errors', resource: @question %>');
<% if !@question.errors.present? %>
  $('.question').html('<%= j render @question %>');
<% end %>

$('.question_links').html("<%= j render partial: 'links_list' %>");