config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  use_doorkeeper
  devise_for :users

  concern :votable do
    member do
      post :vote_up, :vote_down
      delete :cancel_vote
    end
  end

  concern :commentable do
    resources :comments, only: :create, shallow: true
  end

  resources :questions, concerns: %i[votable commentable] do
    resource :subscription, only: %i[create destroy]
    resources :answers, concerns: %i[votable commentable], shallow: true, only: [:create, :update, :destroy] do
      patch :choose_the_best, on: :member
    end
  end

  resources :attachments, only: [:destroy]
  resources :links, only: [:destroy]
  resources :badges, only: [:index]

  root to: 'questions#index'

  namespace :api do
    namespace :v1 do
      resources :profiles, only: [] do
        collection do
          get :me
          get :all
        end
      end

      resources :questions, only: %i[index show create update destroy], shallow: true do
        resources :answers, only: %i[index show create update destroy]
      end
    end
  end

  mount ActionCable.server => '/cable'
end

app/models/answer.rb
class Answer < ApplicationRecord
  include Votable
  include Commentable
  
  default_scope -> { order(best: :desc) }

  belongs_to :user
  belongs_to :question

  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank
  
  validates :body, presence: true

  after_save :notify

  def choose_the_best
    transaction do
      question.answers.where(best: true).update_all(best: false)
      update!(best: true)
      question.badge&.update!(user: user)
    end
  end

  private

  def notify
    AnswerNotificationJob.perform_later(self)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController 
  before_action :authenticate_user!
  before_action :load_answer, only: [:update, :destroy, :choose_the_best]

  after_action :publish_answer, only: [:create]

  include Voted

  authorize_resource

  def create
    @answer = question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    authorize! :update, @answer
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    authorize! :destroy, @answer
    @answer.destroy
  end

  def choose_the_best
    authorize! :choose_the_best, @answer
    @answer.choose_the_best
  end

  private

  def question
    @question ||= Question.find(params[:question_id])
  end

  def load_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: [:name, :url, :id, :_destroy])
  end

  def publish_answer
    return if @answer.errors.any?

    ActionCable.server.broadcast(
      "question#{@answer.question.id}",
      answer: @answer,
      question_author_id: @answer.question.user.id
    )
  end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :load_question, only: %i[index create]
  before_action :load_answer, only: %i[show update destroy]

  def index
    @answers = @question.answers
    authorize! :read, @answers
    render json: @answers
  end

  def show
    authorize! :read, @answer
    render json: @answer
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_resource_owner

    authorize! :create, @answer
    @answer.save
    render json: @answer
  end

  def update
    authorize! :update, @answer
    
    @answer.update!(answer_params)
    render json: @answer
  end

  def destroy
    authorize! :destroy, @answer

    @answer.destroy
    render json: @answer
  end

  private

  def load_answer
    @answer = Answer.find(params[:id])
  end

  def load_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, links_attributes: [:id, :name, :url, :_destroy])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
div id = "answer-#{answer.id}" class=('best' if answer.best)
  - if answer.persisted?
    p= answer.body
    .links
      p Links:
      ul
        - answer.links.each do |link|
          div class="link-#{link.id}"
            li= link_to link.name, link.url
            - if can?(:destroy, answer)
              p= link_to 'Delete link', link_path(link), method: :delete, remote: true
    - if answer.files.attached?
      - answer.files.each do |file|
        p= link_to file.filename.to_s, url_for(file)
  
    .answer_comments
      = render 'comments/comments', resource: answer
    .add_comment
      = render 'comments/form', resource: answer

    .vote
      p Vote:
      div class="#{answer.class}-#{answer.id}"
        .rating
          =  "rating: #{answer.rating}"
        - unless current_user&.author_of?(answer)
          .voting
            = link_to 'up', polymorphic_path(answer, action: :vote_up), 
                            method: :post, 
                            remote: true, 
                            data: { type: :json }
            span= ' | '
            = link_to 'down', polymorphic_path(answer, action: :vote_down), 
                              method: :post, 
                              remote: true, 
                              data: { type: :json }
          .re-vote
            = link_to 'cancel your vote', polymorphic_path(answer, action: :cancel_vote),
                                          class: "cancel-vote-link #{'hidden' unless current_user&.already_voted?(answer.id)}", 
                                          method: :delete, remote: true, data: {type: :json}
  - if current_user&.author_of?(answer)
    p= link_to 'Delete answer', answer_path(answer), method: :delete, remote: true
    p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }
    p= link_to 'The best', choose_the_best_answer_path(answer), class: 'best-answer', data: { answer_id: answer.id }, method: :patch, remote: true
    = form_with model: answer, class: 'hidden', html: { id: "edit-answer-#{answer.id}" } do |f|
      = f.label :body, 'Your answer'
      = f.text_area :body
      = f.label :files
      = f.file_field :files, multiple: true, direct_upload: true
      = f.fields_for :links do |l|
      .links
        = link_to_add_association 'Add link', f, :links, partial: 'questions/link_fields'
      = f.submit 'Save'

app/views/answers/choose_the_best.js.erb
<% if @answer.best? %>
  $('<%="#answer-#{ @answer.id }" %>').addClass('best');
  $('#answer-<%= @answer.id %>').remove();
  $('.answers').prepend('<%= j render @answer %>');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
<% if @answer.persisted? %>
  $(".answers").append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
<% if @answer.destroyed? %>
  $('#answer-' + <%= @answer.id %>).remove();
<% end %>

app/views/answers/update.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
<% if !@answer.errors.present? %>
  $('.answers').html('<%= j render @question.answers %>');
<% end %>